LOGIN = "https://leetcode.com/accounts/login/"
LOGOUT = "https://leetcode.com/accounts/logout/"
CHECKIN = "https://leetcode.com/points/api/checkin/"
PROBLEMS = "https://leetcode.com/api/problems/all/"
SUBMIT = "https://leetcode.com/problems/%s/submit/"
SUBMISSION_STATUS = "https://leetcode.com/submissions/detail/%d/check/"
DESCRIPTION = "https://leetcode.com/problems/%s/description/"
